language: java

jdk: oraclejdk8

dist: trusty

before_install:
  - sudo wget http://master.dl.sourceforge.net/project/d-apt/files/d-apt.list -O /etc/apt/sources.list.d/d-apt.list
  - wget -qO - https://dlang.org/d-keyring.gpg | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq --force-yes dmd-bin dub dcd dfix dfmt dscanner

env:
  global:
  - ORG_GRADLE_PROJECT_downloadIdeaSources=false
  matrix:
  - ORG_GRADLE_PROJECT_ideaVersion=LATEST-EAP-SNAPSHOT
  - ORG_GRADLE_PROJECT_ideaVersion=2017.2
  - ORG_GRADLE_PROJECT_ideaVersion=2017.1.5
  - ORG_GRADLE_PROJECT_ideaVersion=2017.1.4
  - ORG_GRADLE_PROJECT_ideaVersion=2017.1.3
  - ORG_GRADLE_PROJECT_ideaVersion=2017.1.2
  - ORG_GRADLE_PROJECT_ideaVersion=2017.1.1
  - ORG_GRADLE_PROJECT_ideaVersion=2017.1

matrix:
  allow_failures:
  - env: ORG_GRADLE_PROJECT_ideaVersion=LATEST-EAP-SNAPSHOT

## pull requests skip the deployment step
jobs:
  include:
    - stage: Deploy EAP
      env: ORG_GRADLE_PROJECT_ideaVersion=2017.1
      script: ORG_GRADLE_PROJECT_publishChannels=eap ORG_GRADLE_PROJECT_version=1.13-eap$TRAVIS_BUILD_NUMBER ./gradlew publishPlugin
      on:
        branch: master
    - stage: Release
      env: ORG_GRADLE_PROJECT_ideaVersion=2017.1
      script: ORG_GRADLE_PROJECT_version=$TRAVIS_TAG ./gradlew publishPlugin
      on:
        tags: true

