language: java

jdk: oraclejdk8

dist: trusty

before_cache:
 - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

before_install:
  - sudo wget http://master.dl.sourceforge.net/project/d-apt/files/d-apt.list -O /etc/apt/sources.list.d/d-apt.list
  - wget -qO - https://dlang.org/d-keyring.gpg | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq --force-yes dmd-bin dub dcd dfix dfmt dscanner

env:
  global:
  - ORG_GRADLE_PROJECT_downloadIdeaSources=false

jobs:
  include:
    - stage: Build and Test
      env: ORG_GRADLE_PROJECT_ideaVersion=181-SNAPSHOT
    - env: ORG_GRADLE_PROJECT_ideaVersion=2017.3
    - env: ORG_GRADLE_PROJECT_ideaVersion=2017.2.6
    - env: ORG_GRADLE_PROJECT_ideaVersion=2017.2.5
    - stage: Test Coverage
      script: ./gradlew cobertura coveralls
    - stage: Deploy EAP
      script: skip
      env: ORG_GRADLE_PROJECT_ideaVersion=2017.2
      deploy:
        provider: script
        skip_cleanup: true
        script: ORG_GRADLE_PROJECT_publishChannels=eap ORG_GRADLE_PROJECT_version=1.15.3-eap$TRAVIS_BUILD_NUMBER ./gradlew :publishPlugin
        on:
          branch: develop
    - stage: Deploy new Release
      script: skip
      env: ORG_GRADLE_PROJECT_ideaVersion=2017.2
      deploy:
        provider: script
        skip_cleanup: true
        script: ./gradlew publishPlugin
        on:
          branch: master
  allow_failures:
    - env: ORG_GRADLE_PROJECT_ideaVersion=181-SNAPSHOT
