language: java

jdk: oraclejdk8

dist: trusty

before_cache:
 - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

## commented out as part of https://github.com/intellij-dlanguage/intellij-dlanguage/issues/490
#before_install:
#  - sudo apt-get install -y dpkg
#  - sudo wget http://master.dl.sourceforge.net/project/d-apt/files/d-apt.list -O /etc/apt/sources.list.d/d-apt.list
#  - sudo apt-get update --allow-insecure-repositories && sudo apt-get -y --allow-unauthenticated install --reinstall d-apt-keyring
#  - sudo apt-get update && sudo apt-get install dmd-compiler dub

env:
  global:
  - ORG_GRADLE_PROJECT_downloadIdeaSources=false

jobs:
  include:
    - stage: Build and Test
      env: ORG_GRADLE_PROJECT_ideaVersion=LATEST-EAP-SNAPSHOT
    - env: ORG_GRADLE_PROJECT_ideaVersion=2020.3
    - env: ORG_GRADLE_PROJECT_ideaVersion=2020.2.4
    - env: ORG_GRADLE_PROJECT_ideaVersion=2020.2

#    - stage: Deploy EAP
#      if: branch = develop
#      script: skip
#      env: ORG_GRADLE_PROJECT_ideaVersion=2020.2
#      deploy:
#        provider: script
#        skip_cleanup: true
#        script: ORG_GRADLE_PROJECT_publishChannels=eap ORG_GRADLE_PROJECT_version=1.19.1-eap$TRAVIS_BUILD_NUMBER ./gradlew :publishPlugin
#        on:
#          branch: develop

#    - stage: Deploy new Release
#      if: branch = master
#      script: skip
#      #env: ORG_GRADLE_PROJECT_ideaVersion=2020.2
#      deploy:
#        provider: script
#        skip_cleanup: true
#        script: ./gradlew publishPlugin
#        on:
#          branch: master

  allow_failures:
    - env: ORG_GRADLE_PROJECT_ideaVersion=LATEST-EAP-SNAPSHOT
