[versions]
# libraries
annotations = "26.0.2-1"
gson = "2.13.+"
junit = "4.13+"
junit-vintage = "6.0+"
mockito-kotlin = "6.1+"
sentry = "8+"

# plugins
gradleIntelliJPlatformPlugin = "2.10.0"
grammarkit = "2022.3.2.2"
kotlin = "2.2.+"
kover = "0.9.2"
coverallsJacoco = "1.2.20"

[plugins]
gradleIntelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "gradleIntelliJPlatformPlugin" }
gradleIntelliJModule = { id = "org.jetbrains.intellij.platform.module", version.ref = "gradleIntelliJPlatformPlugin" }
grammarkit = { id = "org.jetbrains.grammarkit", version.ref = "grammarkit" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
coverallsJacoco = { id = "com.github.nbaztec.coveralls-jacoco", version.ref = "coverallsJacoco" }

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit = { module = "junit:junit", version.ref = "junit" }
junit-engine = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit-vintage" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }
sentry = { module ="io.sentry:sentry", version.ref = "sentry" }
